__merge__: ../../api/comp_metric.yaml
name: mean_rowwise_error
info:
  metrics:
    - name: mean_rowwise_rmse
      label: Mean Rowwise RMSE
      summary: The mean of the root mean squared error (RMSE) of each row in the matrix.
      description: |
        We use the **Mean Rowwise Root Mean Squared Error** to score submissions, computed as follows:

        $$
        \textrm{MRRMSE} = \frac{1}{R}\sum_{i=1}^R\left(\frac{1}{n} \sum_{j=1}^{n} (y_{ij} - \widehat{y}_{ij})^2\right)^{1/2}
        $$

        where $(R)$ is the number of scored rows, and $(y_{ij})$ and $(\widehat{y}_{ij})$ are the actual and predicted values, respectively, for row $(i)$ and column $(j)$, and $(n)$ bis the number of columns.
      min: 0
      max: +.inf
      maximize: false
      references:
        bibtex: |
          @article{slazata2024benchmark,
            title = {A benchmark for prediction of transcriptomic responses to chemical perturbations across cell types},
            author = {Artur Szałata and Andrew Benz and Robrecht Cannoodt and Mauricio Cortes and Jason Fong and Sunil Kuppasani and Richard Lieberman and Tianyu Liu and Javier A. Mas-Rosario and Rico Meinl and Jalil Nourisa and Jared Tumiel and Tin M. Tunjic and Mengbo Wang and Noah Weber and Hongyu Zhao and Benedict Anchang and Fabian J Theis and Malte D Luecken and Daniel B Burkhardt},
            booktitle = {The Thirty-eight Conference on Neural Information Processing Systems Datasets and Benchmarks Track},
            year = {2024},
            url = {https://openreview.net/forum?id=WTI4RJYSVm}
          }
      links: {}
    - name: mean_rowwise_mae
      label: Mean Rowwise MAE
      summary: The mean of the absolute error (MAE) of each row in the matrix.
      description: |
          We use the **Mean Rowwise Absolute Error** to score submissions, computed as follows:

          $$
          \textrm{MRMAE} = \frac{1}{R}\sum_{i=1}^R\left(\frac{1}{n} \sum_{j=1}^{n} |y_{ij} - \widehat{y}_{ij}|\right)
          $$
        
          where $(R)$ is the number of scored rows, and $(y_{ij})$ and $(\widehat{y}_{ij})$ are the actual and predicted values, respectively, for row $(i)$ and column $(j)$, and $(n)$ bis the number of columns.
      min: 0
      max: +.inf
      maximize: false
      references:
        bibtex: |
          @article{slazata2024benchmark,
            title = {A benchmark for prediction of transcriptomic responses to chemical perturbations across cell types},
            author = {Artur Szałata and Andrew Benz and Robrecht Cannoodt and Mauricio Cortes and Jason Fong and Sunil Kuppasani and Richard Lieberman and Tianyu Liu and Javier A. Mas-Rosario and Rico Meinl and Jalil Nourisa and Jared Tumiel and Tin M. Tunjic and Mengbo Wang and Noah Weber and Hongyu Zhao and Benedict Anchang and Fabian J Theis and Malte D Luecken and Daniel B Burkhardt},
            booktitle = {The Thirty-eight Conference on Neural Information Processing Systems Datasets and Benchmarks Track},
            year = {2024},
            url = {https://openreview.net/forum?id=WTI4RJYSVm}
          }
      links: {}
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        packages: proxyC
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]