__merge__: ../../api/comp_metric.yaml
name: mean_rowwise_error
info:
  metrics:
    - name: mean_rowwise_rmse
      label: Mean Rowwise RMSE
      summary: The mean of the root mean squared error (RMSE) of each row in the matrix.
      description: |
        We use the **Mean Rowwise Root Mean Squared Error** to score submissions, computed as follows:

        $$
        \textrm{MRRMSE} = \frac{1}{R}\sum_{i=1}^R\left(\frac{1}{n} \sum_{j=1}^{n} (y_{ij} - \widehat{y}_{ij})^2\right)^{1/2}
        $$

        where $(R)$ is the number of scored rows, and $(y_{ij})$ and $(\widehat{y}_{ij})$ are the actual and predicted values, respectively, for row $(i)$ and column $(j)$, and $(n)$ bis the number of columns.
      repository_url: null
      documentation_url: null
      min: 0
      max: "+inf"
      maximize: false
    - name: mean_rowwise_mae
      label: Mean Rowwise MAE
      summary: The mean of the absolute error (MAE) of each row in the matrix.
      description: |
          We use the **Mean Rowwise Absolute Error** to score submissions, computed as follows:

          $$
          \textrm{MRMAE} = \frac{1}{R}\sum_{i=1}^R\left(\frac{1}{n} \sum_{j=1}^{n} |y_{ij} - \widehat{y}_{ij}|\right)
          $$
        
          where $(R)$ is the number of scored rows, and $(y_{ij})$ and $(\widehat{y}_{ij})$ are the actual and predicted values, respectively, for row $(i)$ and column $(j)$, and $(n)$ bis the number of columns.
      repository_url: null
      documentation_url: null
      min: 0
      max: "+inf"
      maximize: false
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.4
    setup:
      - type: r
        packages: proxyC
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]