__merge__: ../../api/comp_control_method.yaml
name: mean_outcome
label: Mean per gene
summary: Baseline method that returns mean of gene's outcomes
description: |
  Baseline method that predicts for a gene the mean of its outcomes of all samples.
resources:
  - type: python_script
    path: script.py
  - path: ../../utils/anndata_to_dataframe.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: [ fastparquet ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]