__merge__: ../../api/comp_method.yaml

name: transformer_ensemble
label: Transformer Ensemble
summary: An ensemble of four transformer models, trained on diverse feature sets, with a cluster-based sampling strategy and robust validation for optimal performance.
description: |
  This method employs an ensemble of four transformer models,
  each with different weights and trained on slightly varying feature sets.
  The feature engineering process involved one-hot encoding of categorical labels,
  target encoding using mean and standard deviation, and enriching the feature set
  with the standard deviation of target variables. Additionally, the dataset was
  carefully examined to ensure data cleanliness. A sophisticated sampling strategy
  based on K-Means clustering was employed to partition the data into training and
  validation sets, ensuring a representative distribution. The model architecture
  leveraged sparse and dense feature encoding, along with a transformer for effective
  learning.
links:
  documentation: https://www.kaggle.com/competitions/open-problems-single-cell-perturbations/discussion/458738
  repository: https://github.com/Eliorkalfon/single_cell_pb
references: {}
info:
  neurips2023_rank: 2
arguments:
  - name: --num_train_epochs
    type: integer
    default: 20000
    description: "Number of training epochs."
    info:
      test_default: 10
  - name: --d_model
    type: integer
    default: 128
    description: "Dimensionality of the model."
  - name: --batch_size
    type: integer
    default: 32
    description: "Batch size."
  - name: --early_stopping
    type: integer
    default: 5000
    description: "Number of epochs to wait for early stopping."
resources:
  - type: python_script
    path: script.py
  - path: models.py
  - path: utils.py
  - path: train.py
engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1.0.0
    setup:
      - type: python
        packages:
          - fastparquet
          - pyarrow
          - pandas~=2.0.3
          - scikit-learn~=1.0.1
          - tqdm~=4.66.1
          - numpy~=1.23
          - matplotlib~=3.5.0
          - PyYAML~=6.0.1
          - lion-pytorch
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, veryhighmem, highcpu, gpu ]
