__merge__: ../../api/comp_control_method.yaml
name: zeros
info:
  label: Zeros
  summary: Baseline method that predicts all zeros
  description: |
    Baseline method that predicts all zeros.
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ fastparquet ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]