__merge__: ../../api/comp_control_method.yaml
name: zeros
label: Zeros
summary: Baseline method that predicts all zeros
description: |
  Baseline method that predicts all zeros.
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: [ fastparquet ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]