name: "convert_kaggle_h5ad_to_parquet"
namespace: "process_dataset"
version: "build_main"
argument_groups:
- name: "Inputs"
  arguments:
  - type: "file"
    name: "--input_train"
    info: null
    example:
    - "resources/neurips-2023-kaggle/12_de_by_cell_type_train.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input_test"
    info: null
    example:
    - "resources/neurips-2023-kaggle/12_de_by_cell_type_test.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input_single_cell_h5ad"
    info: null
    example:
    - "resources/neurips-2023-raw/sc_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Metadata"
  arguments:
  - type: "string"
    name: "--dataset_id"
    description: "Unique identifier of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_name"
    description: "Nicely formatted name."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_url"
    description: "Link to the original source of the dataset."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_reference"
    description: "Bibtex reference of the paper in which the dataset was published."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_summary"
    description: "Short description of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_description"
    description: "Long description of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_organism"
    description: "The organism of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output_train_h5ad"
    info: null
    example:
    - "resources/neurips-2023-kaggle/de_train.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output_test_h5ad"
    info: null
    example:
    - "resources/neurips-2023-kaggle/de_test.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output_id_map"
    info: null
    example:
    - "resources/neurips-2023-kaggle/id_map.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
info:
  type: "process_dataset"
  type_info:
    label: "H5AD to Parquet"
    summary: "Convert Kaggle h5ad to parquet"
    description: "Convert dataset from h5ad files into training and test parquet files.\n"
status: "enabled"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_perturbation_prediction"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_images/python:1.1.0"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    packages:
    - "fastparquet"
    - "pandas"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/process_dataset/convert_kaggle_h5ad_to_parquet/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/process_dataset/convert_kaggle_h5ad_to_parquet"
  executable: "target/nextflow/process_dataset/convert_kaggle_h5ad_to_parquet/main.nf"
  viash_version: "0.9.0-RC6"
  git_commit: "02def5146d3342920487a10adc043309d064e95c"
  git_remote: "https://github.com/openproblems-bio/task_perturbation_prediction"
package_config:
  name: "task_perturbation_prediction"
  version: "build_main"
  description: "Predicting how small molecules change gene expression in different\
    \ cell types.\n"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources/perturbation_prediction/datasets"
      dest: "resources/datasets"
  viash_version: "0.9.0-RC6"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }"
  keywords:
  - "single-cell"
  - "perturbation prediction"
  - "perturbation"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_perturbation_prediction"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_perturbation_prediction/issues"
