name: compute_pseudobulk
namespace: "process_dataset"
info:
  type: process_dataset
  type_info:
    label: Pseudobulk
    summary: Compute pseudobulk data
    description: |
      Compute pseudobulk data for the perturbation regression task.
arguments:
  - name: --input
    type: file
    required: true
    direction: input
    example: resources/neurips-2023-raw/sc_counts.h5ad
  - name: --output
    type: file
    required: true
    direction: output
    example: resources/datasets/neurips-2023-data/pseudobulk.h5ad
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ pyarrow ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
