__merge__: ../../api/comp_control_method.yaml
name: sample
info:
  label: Sample
  summary: Sample predictions from the training data
  description: |
    This method samples the training data to generate predictions.
  preferred_normalization: counts
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.4
    setup:
      - type: r
        cran: [ arrow, dplyr ]
      - type: python
        packages: [ fastparquet ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]