name: lgc_ensemble_predict
namespace: methods
arguments:
  - name: --train_data_aug_dir
    type: file
    required: true
    direction: input
  - name: --model_files
    type: file
    required: true
    direction: input
    example: model.pt
    multiple: true
  - name: --id_map
    type: file
    required: true
    direction: input
  - name: --output
    type: file
    required: true
    direction: output
resources:
  - type: python_script
    path: script.py
  - path: ../lgc_ensemble_helpers/helper_classes.py
  - path: ../lgc_ensemble_helpers/helper_functions.py
  - path: ../lgc_ensemble_helpers/models.py
  - path: ../lgc_ensemble_helpers/predict.py
  - path: ../lgc_ensemble_helpers/prepare_data.py
  - path: ../lgc_ensemble_helpers/train.py
  - path: ../lgc_ensemble_helpers/divisor_finder.py
  - path: ../../utils/anndata_to_dataframe.py
    
engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1.0.0
    setup:
      - type: python
        packages:
          - torch==2.1.1
          - --index-url
          - https://download.pytorch.org/whl/cu121
      - type: python
        packages:
          - fastparquet
          - pandas==2.1.3
          - pyarrow==14.0.1
          - tqdm==4.66.1
          - scikit-learn==1.3.2
          - transformers==4.35.2
          - matplotlib==3.8.2
          - torch-summary

  - type: native
runners:
  - type: executable
    docker_run_args: ["--shm-size=2g"]
  - type: nextflow
    directives:
      label: [hightime, veryhighmem, highcpu, highsharedmem, gpu]
