name: filter_vars
namespace: "process_dataset"
info:
  type: process_dataset
  type_info:
    label: Filter variables
    summary: Remove low-quality variables from the dataset
    description: |
      This task removes low-quality variables from the dataset.
arguments:
  - name: --input
    type: file
    required: true
    direction: input
    example: resources/neurips-2023-raw/pseudobulk.h5ad
  - name: --output
    type: file
    required: true
    direction: output
    example: resources/datasets/neurips-2023-data/pseudobulk_cleaned.h5ad
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_images/r:1.1.0
    setup:
      - type: r
        cran: [ edgeR, limma, dplyr, tidyr, purrr, tibble ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
