name: "run_stability_analysis"
namespace: "workflows"
version: "build_main"
argument_groups:
- name: "Inputs"
  arguments:
  - type: "file"
    name: "--sc_counts"
    info:
      label: "Single Cell Counts"
      summary: "Anndata with the counts of the whole dataset."
      file_type: "h5ad"
      slots:
        obs:
        - name: "dose_uM"
          description: "Dose in micromolar."
          type: "integer"
          required: true
        - name: "timepoint_hr"
          description: "Time point measured in hours."
          type: "float"
          required: true
        - name: "raw_cell_id"
          description: "Original cell identifier."
          type: "string"
          required: true
        - name: "hashtag_id"
          description: "Identifier for hashtag oligo."
          type: "string"
          required: true
        - name: "well"
          description: "Well location in the plate."
          type: "string"
          required: true
        - name: "container_format"
          description: "Format of the container (e.g., 96-well plate)."
          type: "string"
          required: true
        - name: "row"
          description: "Row in the plate."
          type: "string"
          required: true
        - name: "col"
          description: "Column in the plate."
          type: "integer"
          required: true
        - name: "plate_name"
          description: "Name of the plate."
          type: "string"
          required: true
        - name: "cell_id"
          description: "Unique cell identifier."
          type: "string"
          required: true
        - name: "cell_type"
          description: "Type of cell (e.g., B cells, T cells CD4+)."
          type: "string"
          required: true
        - name: "split"
          description: "Dataset split type (e.g., control, treated)."
          type: "string"
          required: true
        - name: "donor_id"
          description: "Identifier for the donor."
          type: "string"
          required: true
        - name: "sm_name"
          description: "Name of the small molecule used for treatment."
          type: "string"
          required: true
        obsm:
        - name: "HTO_clr"
          description: "Corrected counts for hashing tags."
          type: "matrix"
          required: true
        - name: "X_pca"
          description: "Principal component analysis results."
          type: "matrix"
          required: true
        - name: "X_umap"
          description: "UMAP dimensionality reduction results."
          type: "matrix"
          required: true
        - name: "protein_counts"
          description: "Count data for proteins."
          type: "matrix"
          required: true
        layers:
        - name: "counts"
          description: "Raw count data for each gene across cells."
          type: "matrix"
          required: true
    example:
    - "resources/neurips-2023-raw/sc_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--id"
    description: "Unique identifier of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--layer"
    description: "Which layer to use for prediction and evaluation."
    info: null
    default:
    - "clipped_sign_log10_pval"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Bootstrapping arguments"
  description: "Define the sampling strategy for the stability analysis."
  arguments:
  - type: "integer"
    name: "--bootstrap_num_replicates"
    description: "Number of bootstrap replicates to run."
    info: null
    default:
    - 10
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--bootstrap_obs"
    description: "Whether to sample observations."
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "double"
    name: "--bootstrap_obs_fraction"
    description: "Fraction of the obs of the sc_counts to include in each bootstrap."
    info: null
    default:
    - 1.0
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--bootstrap_obs_replace"
    description: "Whether to sample with replacement."
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--bootstrap_var"
    description: "Whether to sample variables."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "double"
    name: "--bootstrap_var_fraction"
    description: "Fraction of the var of the sc_counts to include in each bootstrap."
    info: null
    default:
    - 1.0
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--bootstrap_var_replace"
    description: "Whether to sample with replacement."
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--scores"
    description: "A yaml file containing the scores of each of the methods"
    info: null
    default:
    - "stability_uns.yaml"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
- name: "Arguments"
  arguments:
  - type: "string"
    name: "--method_ids"
    description: "A list of method ids to run. If not specified, all methods will\
      \ be run."
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--metric_ids"
    description: "A list of metric ids to run. If not specified, all metric will be\
      \ run."
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
- type: "file"
  path: "task_info.yaml"
info: null
status: "enabled"
dependencies:
- name: "process_dataset/bootstrap"
  repository:
    type: "local"
- name: "workflows/process_dataset"
  repository:
    type: "local"
- name: "workflows/run_benchmark"
  repository:
    type: "local"
repositories:
- type: "github"
  name: "openproblemsv2"
  repo: "openproblems-bio/openproblems-v2"
  tag: "main_build"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_perturbation_prediction"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'\ntrace {\n    enabled = true\n    overwrite\
      \ = true\n    file = \"${params.publish_dir}/trace.txt\"\n}"
  debug: false
  container: "docker"
build_info:
  config: "src/workflows/run_stability_analysis/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/run_stability_analysis"
  executable: "target/nextflow/workflows/run_stability_analysis/main.nf"
  viash_version: "0.9.0-RC6"
  git_commit: "02def5146d3342920487a10adc043309d064e95c"
  git_remote: "https://github.com/openproblems-bio/task_perturbation_prediction"
  dependencies:
  - "target/nextflow/process_dataset/bootstrap"
  - "target/nextflow/workflows/process_dataset"
  - "target/nextflow/workflows/run_benchmark"
package_config:
  name: "task_perturbation_prediction"
  version: "build_main"
  description: "Predicting how small molecules change gene expression in different\
    \ cell types.\n"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources/perturbation_prediction/datasets"
      dest: "resources/datasets"
  viash_version: "0.9.0-RC6"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }"
  keywords:
  - "single-cell"
  - "perturbation prediction"
  - "perturbation"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_perturbation_prediction"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_perturbation_prediction/issues"
