name: "run_stability_analysis"
namespace: "workflows"
version: "build_main"
argument_groups:
- name: "Inputs"
  arguments:
  - type: "file"
    name: "--sc_counts"
    label: "Single Cell Counts"
    summary: "Anndata with the counts of the whole dataset."
    info:
      format:
        type: "h5ad"
        obs:
        - name: "dose_uM"
          description: "Dose in micromolar."
          type: "integer"
          required: true
        - name: "timepoint_hr"
          description: "Time point measured in hours."
          type: "float"
          required: true
        - name: "raw_cell_id"
          description: "Original cell identifier."
          type: "string"
          required: true
        - name: "hashtag_id"
          description: "Identifier for hashtag oligo."
          type: "string"
          required: true
        - name: "well"
          description: "Well location in the plate."
          type: "string"
          required: true
        - name: "container_format"
          description: "Format of the container (e.g., 96-well plate)."
          type: "string"
          required: true
        - name: "row"
          description: "Row in the plate."
          type: "string"
          required: true
        - name: "col"
          description: "Column in the plate."
          type: "integer"
          required: true
        - name: "plate_name"
          description: "Name of the plate."
          type: "string"
          required: true
        - name: "cell_id"
          description: "Unique cell identifier."
          type: "string"
          required: true
        - name: "cell_type"
          description: "Type of cell (e.g., B cells, T cells CD4+)."
          type: "string"
          required: true
        - name: "split"
          description: "Dataset split type (e.g., control, treated)."
          type: "string"
          required: true
        - name: "donor_id"
          description: "Identifier for the donor."
          type: "string"
          required: true
        - name: "sm_name"
          description: "Name of the small molecule used for treatment."
          type: "string"
          required: true
        obsm:
        - name: "HTO_clr"
          description: "Corrected counts for hashing tags."
          type: "matrix"
          required: true
        - name: "X_pca"
          description: "Principal component analysis results."
          type: "matrix"
          required: true
        - name: "X_umap"
          description: "UMAP dimensionality reduction results."
          type: "matrix"
          required: true
        - name: "protein_counts"
          description: "Count data for proteins."
          type: "matrix"
          required: true
        layers:
        - name: "counts"
          description: "Raw count data for each gene across cells."
          type: "matrix"
          required: true
    example:
    - "resources/neurips-2023-raw/sc_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--id"
    description: "Unique identifier of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--layer"
    description: "Which layer to use for prediction and evaluation."
    info: null
    default:
    - "clipped_sign_log10_pval"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Bootstrapping arguments"
  description: "Define the sampling strategy for the stability analysis."
  arguments:
  - type: "integer"
    name: "--bootstrap_num_replicates"
    description: "Number of bootstrap replicates to run."
    info: null
    default:
    - 10
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--bootstrap_obs"
    description: "Whether to sample observations."
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "double"
    name: "--bootstrap_obs_fraction"
    description: "Fraction of the obs of the sc_counts to include in each bootstrap."
    info: null
    default:
    - 1.0
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--bootstrap_obs_replace"
    description: "Whether to sample with replacement."
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--bootstrap_var"
    description: "Whether to sample variables."
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "double"
    name: "--bootstrap_var_fraction"
    description: "Fraction of the var of the sc_counts to include in each bootstrap."
    info: null
    default:
    - 1.0
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--bootstrap_var_replace"
    description: "Whether to sample with replacement."
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--scores"
    description: "A yaml file containing the scores of each of the methods"
    info: null
    default:
    - "stability_uns.yaml"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
- name: "Arguments"
  arguments:
  - type: "string"
    name: "--method_ids"
    description: "A list of method ids to run. If not specified, all methods will\
      \ be run."
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--metric_ids"
    description: "A list of metric ids to run. If not specified, all metric will be\
      \ run."
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
- type: "file"
  path: "_viash.yaml"
info: null
status: "enabled"
dependencies:
- name: "process_dataset/bootstrap"
  repository:
    type: "local"
- name: "workflows/process_dataset"
  repository:
    type: "local"
- name: "workflows/run_benchmark"
  repository:
    type: "local"
repositories:
- type: "github"
  name: "openproblemsv2"
  repo: "openproblems-bio/openproblems-v2"
  tag: "main_build"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_perturbation_prediction"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'\ntrace {\n    enabled = true\n    overwrite\
      \ = true\n    file = \"${params.publish_dir}/trace.txt\"\n}"
  debug: false
  container: "docker"
build_info:
  config: "src/workflows/run_stability_analysis/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/run_stability_analysis"
  executable: "target/nextflow/workflows/run_stability_analysis/main.nf"
  viash_version: "0.9.0"
  git_commit: "2fa44462b1e7d530bad703c4a20ed22b49d3705e"
  git_remote: "https://github.com/openproblems-bio/task_perturbation_prediction"
  dependencies:
  - "target/nextflow/process_dataset/bootstrap"
  - "target/nextflow/workflows/process_dataset"
  - "target/nextflow/workflows/run_benchmark"
package_config:
  name: "task_perturbation_prediction"
  version: "build_main"
  label: "Perturbation Prediction"
  summary: "Predicting how small molecules change gene expression in different cell\
    \ types."
  description: "Human biology can be complex, in part due to the function and interplay\
    \ of the body's\napproximately 37 trillion cells, which are organized into tissues,\
    \ organs, and systems.\nHowever, recent advances in single-cell technologies have\
    \ provided unparalleled insight\ninto the function of cells and tissues at the\
    \ level of DNA, RNA, and proteins. Yet\nleveraging single-cell methods to develop\
    \ medicines requires mapping causal links\nbetween chemical perturbations and\
    \ the downstream impact on cell state. These experiments\nare costly and labor\
    \ intensive, and not all cells and tissues are amenable to\nhigh-throughput transcriptomic\
    \ screening. If data science could help accurately predict\nchemical perturbations\
    \ in new cell types, it could accelerate and expand the development\nof new medicines.\n\
    \nSeveral methods have been developed for drug perturbation prediction, most of\
    \ which are\nvariations on the autoencoder architecture (Dr.VAE, scGEN, and ChemCPA).\
    \ However, these\nmethods lack proper benchmarking datasets with diverse cell\
    \ types to determine how well\nthey generalize. The largest available training\
    \ dataset is the NIH-funded Connectivity\nMap (CMap), which comprises over 1.3M\
    \ small molecule perturbation measurements. However,\nthe CMap includes observations\
    \ of only 978 genes, less than 5% of all genes. Furthermore,\nthe CMap data is\
    \ comprised almost entirely of measurements in cancer cell lines, which\nmay not\
    \ accurately represent human biology.\n\nThis task aims to predict how small molecules\
    \ change gene expression in different cell\ntypes. This task was a [Kaggle competition](https://www.kaggle.com/competitions/open-problems-single-cell-perturbations/overview)\n\
    as part of the [NeurIPS 2023 competition track](https://neurips.cc/virtual/2023/competition/66586).\n\
    \nThe task is to predict the gene expression profile of a cell after a small molecule\n\
    perturbation. For this competition, we designed and generated a novel single-cell\n\
    perturbational dataset in human peripheral blood mononuclear cells (PBMCs). We\n\
    selected 144 compounds from the Library of Integrated Network-Based Cellular Signatures\n\
    (LINCS) Connectivity Map dataset ([PMID: 29195078](https://pubmed.ncbi.nlm.nih.gov/29195078/))\n\
    and measured single-cell gene\nexpression profiles after 24 hours of treatment.\
    \ The experiment was repeated in three\nhealthy human donors, and the compounds\
    \ were selected based on diverse transcriptional\nsignatures observed in CD34+\
    \ hematopoietic stem cells (data not released). We performed\nthis experiment\
    \ in human PBMCs because the cells are commercially available with\npre-obtained\
    \ consent for public release and PBMCs are a primary, disease-relevant tissue\n\
    that contains multiple mature cell types (including T-cells, B-cells, myeloid\
    \ cells,\nand NK cells) with established markers for annotation of cell types.\
    \ To supplement this\ndataset, we also measured cells from each donor at baseline\
    \ with joint scRNA and\nsingle-cell chromatin accessibility measurements using\
    \ the 10x Multiome assay. We hope\nthat the addition of rich multi-omic data for\
    \ each donor and cell type at baseline will\nhelp establish biological priors\
    \ that explain the susceptibility of particular genes to\nexhibit perturbation\
    \ responses in difference biological contexts.\n"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources/task_perturbation_prediction/datasets"
      dest: "resources/datasets"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }"
  authors:
  - name: "Artur Szałata"
    roles:
    - "author"
    info:
      github: "szalata"
      orcid: "000-0001-8413-234X"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Daniel Burkhardt"
    roles:
    - "author"
    info:
      github: "dburkhardt"
      orcid: "0000-0001-7744-1363"
  - name: "Malte D. Luecken"
    roles:
    - "author"
    info:
      github: "LuckyMD"
      orcid: "0000-0001-7464-7921"
  - name: "Tin M. Tunjic"
    roles:
    - "contributor"
    info:
      github: "ttunja"
      orcid: "0000-0001-8842-6548"
  - name: "Mengbo Wang"
    roles:
    - "contributor"
    info:
      github: "wangmengbo"
      orcid: "0000-0002-0266-9993"
  - name: "Andrew Benz"
    roles:
    - "author"
    info:
      github: "andrew-benz"
      orcid: "0009-0002-8118-1861"
  - name: "Tianyu Liu"
    roles:
    - "contributor"
    info:
      github: "HelloWorldLTY"
      orcid: "0000-0002-9412-6573"
  - name: "Jalil Nourisa"
    roles:
    - "contributor"
    info:
      github: "janursa"
      orcid: "0000-0002-7539-4396"
  - name: "Rico Meinl"
    roles:
    - "contributor"
    info:
      github: "ricomnl"
      orcid: "0000-0003-4356-6058"
  keywords:
  - "single-cell"
  - "perturbation prediction"
  - "perturbation"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  references:
    bibtex:
    - "@article{slazata2024benchmark,\n  title = {A benchmark for prediction of transcriptomic\
      \ responses to chemical perturbations across cell types},\n  author = {Artur\
      \ Szałata and Andrew Benz and Robrecht Cannoodt and Mauricio Cortes and Jason\
      \ Fong and Sunil Kuppasani and Richard Lieberman and Tianyu Liu and Javier A.\
      \ Mas-Rosario and Rico Meinl and Jalil Nourisa and Jared Tumiel and Tin M. Tunjic\
      \ and Mengbo Wang and Noah Weber and Hongyu Zhao and Benedict Anchang and Fabian\
      \ J Theis and Malte D Luecken and Daniel B Burkhardt},\n  booktitle = {The Thirty-eight\
      \ Conference on Neural Information Processing Systems Datasets and Benchmarks\
      \ Track},\n  year = {2024},\n  url = {https://openreview.net/forum?id=WTI4RJYSVm}\n\
      }\n"
  links:
    repository: "https://github.com/openproblems-bio/task_perturbation_prediction"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_perturbation_prediction/issues"
