name: "compute_pseudobulk"
namespace: "process_dataset"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input"
    info: null
    example:
    - "resources/neurips-2023-raw/sc_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    info: null
    example:
    - "resources/datasets/neurips-2023-data/pseudobulk.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
info:
  type: "process_dataset"
  type_info:
    label: "Pseudobulk"
    summary: "Compute pseudobulk data"
    description: "Compute pseudobulk data for the perturbation regression task.\n"
status: "enabled"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_perturbation_prediction"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_images/python:1.1.0"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    packages:
    - "pyarrow"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/process_dataset/compute_pseudobulk/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/process_dataset/compute_pseudobulk"
  executable: "target/nextflow/process_dataset/compute_pseudobulk/main.nf"
  viash_version: "0.9.0-RC6"
  git_commit: "e5a05568a223c55860da3234dc94b0ebbaf08f28"
  git_remote: "https://github.com/openproblems-bio/task_perturbation_prediction"
package_config:
  name: "task_perturbation_prediction"
  version: "build_main"
  description: "Predicting how small molecules change gene expression in different\
    \ cell types.\n"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources/perturbation_prediction/datasets"
      dest: "resources/datasets"
  viash_version: "0.9.0-RC6"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }"
  keywords:
  - "single-cell"
  - "perturbation prediction"
  - "perturbation"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_perturbation_prediction"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_perturbation_prediction/issues"
