name: filter_obs
namespace: "process_dataset"
info:
  type: process_dataset
  type_info:
    label: Filter observations
    summary: Remove low-quality observations from the dataset
    description: |
      This task removes low-quality observations from the dataset.
arguments:
  - name: --input
    type: file
    required: true
    direction: input
    example: resources/neurips-2023-raw/sc_counts.h5ad
  - name: --output
    type: file
    required: true
    direction: output
    example: resources/datasets/neurips-2023-data/sc_counts_cleaned.h5ad
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        cran: [ dplyr, tidyr, purrr, tibble ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
