name: Build

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
    inputs:
      version:
        description: |
          The version of the project to build. Example: `1.0.3`.
          
          If not provided, a development build with a version name
          based on the branch name will be built. Otherwise, a release
          build with the provided version will be built.
        required: false

jobs:
  build:
    uses: openproblems-bio/actions/.github/workflows/build.yml@main
    with:
      version: ${{ github.event.inputs.version }}
